
spring:
  velocity:
    resourceLoaderPath: 'classpath:/templates/'
    suffix: .vm
    cache: false
    check-template-location: true
    content-type: text/html
    charset: UTF-8
    properties:
      input:
        encoding: UTF-8
      output:
       encoding: UTF-8



